<?php
    $myarray = array(10,-2,13,454,10,34,705,6,12,344,67,88,499,340,67,2,228,1116,923);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    //repeat this procedure in many times
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    for($x=0;$x<1000;$x++){
        asort($myarray);
        arsort($myarray);
    }
    print_r($myarray);
    

?>
